name: workshop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Compare dart object
  equatable: ^2.0.5
  # State management
  flutter_bloc: ^8.1.3
  # Service locator
  get_it: ^7.6.0
  # Database
  floor: ^1.4.2
  # Make request to api
  retrofit: ^4.0.1
  # Hook
  flutter_hooks: ^0.18.6
  # cached network image
  cached_network_image: ^3.2.3
  # injection
  injectable: ^2.1.2
  # Json Generator
  json_annotation: ^4.8.1
  # class generator
  freezed_annotation: ^2.2.0
  # Router
  go_router: ^8.0.5
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  # Change Language
  flutter_localizations:
    sdk: flutter
  intl: any
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Code generator
  retrofit_generator: ^7.0.1
  floor_generator: ^1.4.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.2
  freezed: ^2.3.5

flutter:
  uses-material-design: true
  generate: true

